/* eslint-disable @next/next/next-script-for-ga */
import type { NextPage } from 'next';
import Head from 'next/head';

import { Livechat } from '@/components/layout';

const Chat: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          Win Wise || Whispa Konnect Limited || Best online betting platform where everyone is a
          WINNER!{' '}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="geo.region" content="NG-LA" />
        <meta name="geo.placename" content="Lagos" />
        <meta name="geo.position" content="6.455058;3.39418" />
        <meta name="ICBM" content="6.455058, 3.39418" />
        <meta
          name="google-site-verification"
          content="Sn7d1l-y9keviyv3WGQk9kyWxaZxg2hBTh4D12KE2WQ"
        />
        <meta name="msvalidate.01" content="412BEB932BFFB159FCA9DE3485A58C56" />
        <link rel="alternate" href="https://www.wisewinn.com/" hrefLang="en-ng" />
        <link rel="icon" href="/favicon.ico" />
        {/* GOOGLE ANALYTICS CODE */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZB82DT448L"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: ` window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
          
            gtag('config', 'G-ZB82DT448L');`,
          }}
        ></script>
        {/* END OF GOOGLE ANALYTICS CODE */}
        {/* HOT JAR  */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3253997,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');`,
          }}
        />
        {/* Prove Src  */}
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(o,i){window.provesrc&&window.console&&console.error&&console.error("ProveSource is included twice in this page."),provesrc=window.provesrc={dq:[],display:function(){this.dq.push(arguments)}},o._provesrcAsyncInit=function(){provesrc.init({apiKey:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI1ZTJkNTQ1NWViZTEwZDNkYmM3OThmYmIiLCJpYXQiOjE2MDY2OTQ0NDV9.JxvE_IUJYd8TBBkEzbgOd63LpPgOfYF-O6KhY222RVI",v:"0.0.4"})};var r=i.createElement("script");r.type="text/javascript",r.async=!0,r["ch"+"ar"+"set"]="UTF-8",r.src="https://cdn.provesrc.com/provesrc.js";var e=i.getElementsByTagName("script")[0];e.parentNode.insertBefore(r,e)}(window,document);`,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-54GPL45');
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-M8P6FKQ');
            `,
          }}
        />{' '}
      </Head>
      <body>
        <Livechat />

        <iframe
          src="https://organizations.minnit.chat/383404469814711/WinWise?embed&nickname="
          style={{ border: 'none', width: '100%', height: '100vh' }}
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          //@ts-expect-error
          // eslint-disable-next-line react/no-unknown-property
          allowTransparency="true"
        ></iframe>
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M8P6FKQ"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
          }}
        />
      </body>
    </>
  );
};

export default Chat;
